export const CACHE_KEYS = {
  REPTILES: 'reptiles',
  REPTILE_REPORTS : 'reptile_reports',
  REPTILE_DETAILS : 'reptile_details',
  SPECIES: 'species',
  MORPHS: 'morphs',
  HEALTH_ENTRIES: 'health_entries',
  HEALTH_LOGS: 'health_logs',
  HEALTH_CATEGORIES : 'health_categories',
  GROWTH_ENTRIES: 'growth_entries',
  BREEDING_PROJECTS: 'breeding_projects',
  BREEDING_PROJECTS_DETAILED: 'breeding_projects_detailed',
  BREEDING_STATS: 'breeding_stats',
  GENETIC_OUTCOMES: 'genetic_outcomes',
  CLUTCHES: 'clutches',
  SALES: 'sales',
  SALES_SUMMARY : 'sales_summary',
  SALES_BY_SPECIES : 'sales_by_species',
  SALES_BY_MORPH : 'sales_by_morph',
  EXPENSES: 'expenses',
  EXPENSES_SUMMARY: 'expenses_summary',
  EXPENSES_BY_CATEGORY: 'expenses_by_category',
  USERS: 'users',
  ACCESS_PROFILES: 'access_profiles',
  PAGES: 'pages',
  FEEDING_SCHEDULES: 'feeding_schedules',
  FEEDING_EVENTS: 'feeding_events',
  FEEDING_EVENTS_LOGS: 'feeding_events_logs',
  FEEDING_STATUS: 'feeding_status',
  FEEDING_SCHEDULE_STATS: 'feeding_schedule_stats',
  FEEDING_REPORTS: 'feeding_reports',
  FEEDING_UPCOMING: 'feeding_upcoming',
  SHEDDING: 'shedding',
  ENCLOSURES: 'enclosures',
  HATCHLINGS: 'hatchlings',
  LIMIT: 'limit',
  CATALOG_ENTRIES: 'catalog_entries',
  CATALOG_SETTINGS: 'catalog_settings',
  OCCUPIED_LOCATIONS: 'occupied_locations',
  ROOMS: 'rooms',
  RACKS: 'racks',
  RACK_LEVELS: 'rack_levels',
  LOCATIONS: 'locations',
  LOCATION_DETAILS: 'location_details',
  GENETIC_CALCULATIONS_HISTORY: 'genetic_calculations_history',
  ORGANIZATION : 'organization',
  BACKUP_LOGS: 'backup_logs',
  BACKUP_HISTORY: 'backup_history',
  SUBSCRIPTION: 'subscription',
} as const