name: Type Check

on:
  pull_request:
    branches:
      - master

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run TypeScript type check
        run: npm run type-check
